### ISSUE TITLE
Custom name for config file

### ISSUE THREAD

**Issue by ganobrega** [nightmode/feri#36]
I don't like so much the name: `feri-config.js`.

So, i want to run something like:

`feri --filename config.js` or `feri --filename feri.js`

It is already possible? I din't find something about this in documentation.

**Comment by nightmode** [comment]
The filename parameter would be a lot of typing but I do like the shorter `feri.js`. So much so I'm going to look into changing the default config file to be `feri.js` and if that doesn't exist it will check for `feri-config.js` for anyone with an older file.

I'm going to look into this today and will let you know how it goes. ^_^

**Comment by nightmode** [comment]
Code is live on GitHub and I'll probably push out an update to NPM later today.

Feri now prefers `feri.js` files including setting one up for you if you run `feri --init`. If Feri can't find a `feri.js` file she will check for an older `feri-config.js` file so any existing users aren't annoyed.

I also like how `feri.js` kinda tells you the name of the program and what command to run vs. the previous `feri-config.js` naming.

Thanks for this issue. Much appreciated. ^_^
