### ISSUE TITLE
Static documentation with Github Pages

### ISSUE THREAD

**Issue by ganobrega** [nightmode/feri#39]
It would be great, if the documentation was hosted in **Github Pages**. 
Using a framework like: **docusaurus** or **docsify**.
The reading and user experience is much better than Github, in addition to having support for multiple languages, navigation bar and advanced search.
The project documentation is very extensive, leaving some people lost.
The `readme.md` of the project could be simplified and leave the documentation responsibility for Github Pages.
Leaving `readme.md` cleaner and exploring further the purposes and goals of the tool.

**Comment by nightmode** [comment]
I definitely feel like the documentation can be improved. Especially for first time users.

I don't think I'd go the GitHub pages route or anything move complex than the current markdown pages being used right now though. I like everything in one place and without any more tech than is being currently used.

If Feri got ridiculously popular I envision a dedicated site with all sorts of videos, interactive goodies, and such. Feri may never get that popular though. ;)
